version: "3.9"

services:
  password_check_service:
    build:
      context: ./password_check
      dockerfile: Dockerfile
    container_name: password_check_container
    ports:
      - "8000:8000"
    volumes:
      - ./password_check:/app
    restart: unless-stopped

  suspicious_service:
    build:
      context: ./suspicious
      dockerfile: Dockerfile
    container_name: suspicious_container
    ports:
      - "8050:8050"
    volumes:
      - ./suspicious:/app
    restart: unless-stopped