sonar.projectKey=kerfaiyass54_vehicule-rental-application
sonar.organization=kerfaiyass54

# Source code
sonar.sources=car_rental/src,vad-front-app/src,vehicle_ai

# Language detection
sonar.sourceEncoding=UTF-8

# Exclusions (important)
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**

# Java specific
sonar.java.binaries=car_rental/target

# Optional but useful
sonar.verbose=true