spring.application.name=account-service
server.port=8101
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ACCOUNT_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/vehicule-app}
spring.elasticsearch.uris=${ACCOUNT_ELASTICSEARCH_URL:http://localhost:9200}
spring.elasticsearch.username=${ACCOUNT_ELASTICSEARCH_USERNAME:elastic}
spring.elasticsearch.password=${ACCOUNT_ELASTICSEARCH_PASSWORD:}
spring.kafka.bootstrap-servers=${ACCOUNT_KAFKA_BOOTSTRAP_SERVERS:localhost:9194}
spring.kafka.consumer.group-id=${ACCOUNT_KAFKA_GROUP:account-service}
spring.kafka.consumer.auto-offset-reset=earliest
keycloak.server-url=${ACCOUNT_KEYCLOAK_SERVER_URL:http://localhost:8180}
keycloak.realm=${ACCOUNT_KEYCLOAK_REALM:vehicule-app}
keycloak.admin-realm=${ACCOUNT_KEYCLOAK_ADMIN_REALM:master}
keycloak.client-id=${ACCOUNT_KEYCLOAK_CLIENT_ID:admin-cli}
keycloak.admin-username=${ACCOUNT_KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin-password=${ACCOUNT_KEYCLOAK_ADMIN_PASSWORD:admin}
account.kafka.topic=${ACCOUNT_KAFKA_TOPIC:keycloak-user-provisioning}
