spring.config.import=optional:file:.env[.properties]


spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}


# =========================================================
# SECURITY / KEYCLOAK RESOURCE SERVER
# =========================================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

jwt.auth.converter.resource-id=${JWT_AUTH_CONVERTER_RESOURCE_ID}
jwt.auth.converter.principal-attribute=${JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE}


# =========================================================
# SWAGGER / OPENAPI
# =========================================================

springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}


# =========================================================
# KEYCLOAK
# =========================================================

keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}

# Client used by the application to communicate with Keycloak
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

# Keycloak admin credentials used by the synchronization service
keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}

# Temporary password assigned to users created during synchronization
keycloak.sync.default-password=${KEYCLOAK_SYNC_DEFAULT_PASSWORD}


# =========================================================
# ELASTICSEARCH
# =========================================================

spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS}
spring.elasticsearch.username=${SPRING_ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${SPRING_ELASTICSEARCH_PASSWORD}


# =========================================================
# APPLICATION
# =========================================================

ip.address=${IP_ADDRESS}
allowed.origin=${ALLOWED_ORIGIN}
suspicious.predict=${SUSPICIOUS_PREDICT}
resource.access=${RESOURCE_ACCESS}