spring.datasource.url=jdbc:postgresql://postgres:5432/vehiculerents
spring.datasource.username=postgres
spring.datasource.password=krkrfrang

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/vehicule-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/vehicule-app/protocol/openid-connect/certs

spring.elasticsearch.uris=http://elasticsearch:9200

suspicious.predict=http://suspicious:8050/predict

allowed.origin=http://frontend