spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}

jwt.auth.converter.resource-id=${JWT_AUTH_CONVERTER_RESOURCE_ID}
jwt.auth.converter.principal-attribute=${JWT_AUTH_CONVERTER_PRINCIPAL_ATTRIBUTE}

springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH}

keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

spring.elasticsearch.uris=${SPRING_ELASTICSEARCH_URIS}
spring.elasticsearch.username=${SPRING_ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${SPRING_ELASTICSEARCH_PASSWORD}

ip.address=${IP_ADDRESS}
allowed.origin=${ALLOWED_ORIGIN}
suspicious.predict=${SUSPICIOUS_PREDICT}
resource.access=${RESOURCE_ACCESS}