#######################################
# .ENV / APPLICATION
#######################################
spring.config.import=optional:file:.env
spring.application.name=${SPRING_APPLICATION_NAME:car_rental}

server.port=${SERVER_PORT:8100}


#######################################
# PostgreSQL
#######################################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}


#######################################
# JPA / Hibernate
#######################################

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#######################################
# Keycloak / OAuth2
#######################################

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI}

jwt.auth.converter.resource-id=${JWT_RESOURCE_ID}
jwt.auth.converter.principal-attribute=${JWT_PRINCIPAL_ATTRIBUTE:preferred_username}


#######################################
# SpringDoc
#######################################

springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/api-docs}


#######################################
# Keycloak Admin
#######################################

keycloak.server-url=${KEYCLOAK_SERVER_URL}
keycloak.realm=${KEYCLOAK_REALM}

keycloak.admin-realm=${KEYCLOAK_ADMIN_REALM}
keycloak.admin-username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin-password=${KEYCLOAK_ADMIN_PASSWORD}

keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

resource.access=${RESOURCE_ACCESS}

keycloak.sync.default-password=${KEYCLOAK_SYNC_DEFAULT_PASSWORD:123456}


#######################################
# Elasticsearch
#######################################

spring.elasticsearch.uris=${ELASTICSEARCH_URI}

spring.elasticsearch.username=${ELASTICSEARCH_USERNAME}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}


#######################################
# Application configuration
#######################################

ip.address=${IP_ADDRESS}

allowed.origin=${ALLOWED_ORIGIN}

suspicious.predict=${SUSPICIOUS_PREDICT_URL}