package com.projecttuto.vehicule_rental.servicesImpl;

import com.projecttuto.vehicule_rental.dto.SupplierAdminDTO;
import com.projecttuto.vehicule_rental.entities.Address;
import com.projecttuto.vehicule_rental.entities.Location;
import com.projecttuto.vehicule_rental.entities.Supplier;
import com.projecttuto.vehicule_rental.enums.AddressStatus;
import com.projecttuto.vehicule_rental.repositories.AddressRepository;
import com.projecttuto.vehicule_rental.repositories.SupplierRepository;
import com.projecttuto.vehicule_rental.services.SupplierManagementService;
import com.projecttuto.vehicule_rental.services.LocationEventPublisher;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

@Service
@Slf4j
@RequiredArgsConstructor
public class SupplierManagementServiceImpl
        implements SupplierManagementService {

    private final SupplierRepository supplierRepository;
    private final AddressRepository addressRepository;
    private final LocationEventPublisher locationEventPublisher;

    @Override
    public SupplierAdminDTO createSupplier(
            SupplierAdminDTO dto
    ) {

        Supplier supplier = new Supplier();

        /*
         * ID is generated by the database.
         * Therefore we intentionally do not set dto.getId().
         */

        supplier.setSupplierName(
                dto.getSuppName()
        );

        supplier.setEmail(
                dto.getEmail()
        );

        supplier.setNationality(
                dto.getNationality()
        );

        supplier.setExperience(
                dto.getExperience()
        );

        supplier.setRole(
                dto.getRole()
        );


        Supplier savedSupplier =
                supplierRepository.save(
                        supplier
                );
        locationEventPublisher.publish("supplier.created", "supplier", savedSupplier.getIdSupplier(), null,
                primaryAssignedLocation(savedSupplier));


        return toDTO(savedSupplier);
    }


    private SupplierAdminDTO toDTO(
            Supplier supplier
    ) {

        SupplierAdminDTO dto =
                new SupplierAdminDTO();

        dto.setId(
                supplier.getIdSupplier()
        );

        dto.setSuppName(
                supplier.getSupplierName()
        );

        dto.setEmail(
                supplier.getEmail()
        );

        dto.setNationality(
                supplier.getNationality()
        );

        dto.setExperience(
                supplier.getExperience()
        );

        dto.setRole(
                supplier.getRole()
        );

        return dto;
    }

    @Override
    public Page<SupplierAdminDTO> getSuppliers(
            int page,
            int size) {

        Pageable pageable = PageRequest.of(page, size);

        return supplierRepository
                .findAll(pageable)
                .map(this::mapToDTO);
    }

    @Override
    public SupplierAdminDTO getSupplier(Long id) {

        Supplier supplier = findSupplierById(id);

        return mapToDTO(supplier);
    }

    @Override
    public SupplierAdminDTO updateSupplier(
            Long id,
            SupplierAdminDTO dto) {

        Supplier supplier = findSupplierById(id);
        Location previousLocation = primaryAssignedLocation(supplier);

        updateSupplierFields(supplier, dto);

        Supplier savedSupplier =
                supplierRepository.save(supplier);
        locationEventPublisher.publish("supplier.updated", "supplier", savedSupplier.getIdSupplier(),
                previousLocation, primaryAssignedLocation(savedSupplier));

        return mapToDTO(savedSupplier);
    }

    @Override
    public void deleteSupplier(Long id) {

        Supplier supplier = findSupplierById(id);
        Location previousLocation = primaryAssignedLocation(supplier);

        supplierRepository.delete(supplier);
        locationEventPublisher.publish("supplier.deleted", "supplier", supplier.getIdSupplier(), previousLocation, null);
    }

    private Supplier findSupplierById(Long id) {

        return supplierRepository.findById(id)
                .orElseThrow(() ->
                        new RuntimeException("Supplier not found"));
    }

    private void updateSupplierFields(
            Supplier supplier,
            SupplierAdminDTO dto) {

        supplier.setSupplierName(
                dto.getSuppName());

        supplier.setNationality(
                dto.getNationality());

        supplier.setExperience(
                dto.getExperience());
    }

    private Location primaryAssignedLocation(Supplier supplier) {
        return addressRepository.findAddressesBySupplier(supplier).stream()
                .filter(address -> address.getAddressStatus() == AddressStatus.ASSIGNED)
                .map(Address::getLocation)
                .findFirst()
                .orElse(null);
    }

    private SupplierAdminDTO mapToDTO(
            Supplier supplier) {

        SupplierAdminDTO dto =
                new SupplierAdminDTO();

        dto.setId(
                supplier.getIdSupplier());

        dto.setSuppName(
                supplier.getSupplierName());

        dto.setEmail(
                supplier.getEmail());

        dto.setNationality(
                supplier.getNationality());

        dto.setExperience(
                supplier.getExperience());

        return dto;
    }
}
