-- ============================================
-- VEHICLE RENTAL DATABASE SCHEMA (CORRECTED)
-- Column names verified against JPA entities
-- ============================================


-- ============================================
-- 1. ADMINS
-- ============================================

CREATE TABLE IF NOT EXISTS admins (
                                      id_admin BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      admin_name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
    );


-- ============================================
-- 2. LOCATIONS
-- ============================================

CREATE TABLE IF NOT EXISTS locations (
                                         id_location BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         location_name VARCHAR(255) NOT NULL,
    country VARCHAR(100),
    position VARCHAR(255),
    id_admin BIGINT,

    CONSTRAINT fk_location_admin
    FOREIGN KEY (id_admin)
    REFERENCES admins(id_admin)
    );


-- ============================================
-- 3. SUPPLIERS
-- ============================================

CREATE TABLE IF NOT EXISTS suppliers (
                                         id_supplier BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         supplier_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    nationality VARCHAR(100),
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    experience INTEGER,
    id_admin BIGINT,

    CONSTRAINT fk_supplier_admin
    FOREIGN KEY (id_admin)
    REFERENCES admins(id_admin),

    CONSTRAINT check_supplier_experience
    CHECK (experience IS NULL OR experience >= 0)
    );


-- ============================================
-- 4. ADDRESSES
-- FIX: Address.java maps this field as @Column(name = "number"),
-- not "address_number". Renamed column + constraint accordingly.
-- ============================================

CREATE TABLE IF NOT EXISTS addresses (
                                         id_address BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         address_status VARCHAR(50) NOT NULL,
    number INTEGER NOT NULL,
    road VARCHAR(255) NOT NULL,
    surface DOUBLE PRECISION,
    id_supplier BIGINT,
    id_location BIGINT,

    CONSTRAINT fk_address_supplier
    FOREIGN KEY (id_supplier)
    REFERENCES suppliers(id_supplier),

    CONSTRAINT fk_address_location
    FOREIGN KEY (id_location)
    REFERENCES locations(id_location),

    CONSTRAINT check_address_status
    CHECK (
              address_status IN (
              'AVAILABLE',
              'UNAVAILABLE'
                                )
    ),

    CONSTRAINT check_address_number
    CHECK (number > 0),

    CONSTRAINT check_address_surface
    CHECK (surface IS NULL OR surface >= 0)
    );


-- ============================================
-- 5. CLIENTS
-- ============================================

CREATE TABLE IF NOT EXISTS clients (
                                       id_client BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       client_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    budget DOUBLE PRECISION,
    age INTEGER,
    nationality VARCHAR(100),
    id_admin BIGINT,
    id_location BIGINT,

    CONSTRAINT fk_client_admin
    FOREIGN KEY (id_admin)
    REFERENCES admins(id_admin),

    CONSTRAINT fk_client_location
    FOREIGN KEY (id_location)
    REFERENCES locations(id_location),

    CONSTRAINT check_client_age
    CHECK (age IS NULL OR age >= 0),

    CONSTRAINT check_client_budget
    CHECK (budget IS NULL OR budget >= 0)
    );


-- ============================================
-- 6. REPAIRERS
-- ============================================

CREATE TABLE IF NOT EXISTS repairs (
                                       id_repair BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       repair_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    id_admin BIGINT,
    id_location BIGINT,

    CONSTRAINT fk_repair_admin
    FOREIGN KEY (id_admin)
    REFERENCES admins(id_admin),

    CONSTRAINT fk_repair_location
    FOREIGN KEY (id_location)
    REFERENCES locations(id_location)
    );


-- ============================================
-- 7. VEHICLES
-- FIX: check_vehicle_top_speed referenced a non-existent
-- column "top_speed". The actual/mapped column (Vehicule.java)
-- is "max_speed" - constraint corrected to reference it.
-- ============================================

CREATE TABLE IF NOT EXISTS vehicles (
                                        id_vehicle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        vehicle_name VARCHAR(255) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    color VARCHAR(50),
    max_speed INTEGER,
    price DOUBLE PRECISION NOT NULL,
    transmission VARCHAR(50) NOT NULL,
    vehicle_status VARCHAR(50) NOT NULL,
    id_supplier BIGINT,

    CONSTRAINT fk_vehicle_supplier
    FOREIGN KEY (id_supplier)
    REFERENCES suppliers(id_supplier),

    CONSTRAINT check_vehicle_price
    CHECK (price >= 0),

    CONSTRAINT check_vehicle_max_speed
    CHECK (max_speed IS NULL OR max_speed >= 0),

    CONSTRAINT check_vehicle_transmission
    CHECK (
              transmission IN (
              'MANUAL',
              'AUTOMATIC'
                              )
    ),

    CONSTRAINT check_vehicle_status
    CHECK (
              vehicle_status IN (
              'TAKEN',
              'AVAILABLE',
              'REPARATION'
                                )
    )
    );


-- ============================================
-- 8. BUYINGS
-- ============================================

CREATE TABLE IF NOT EXISTS buyings (
                                       id_buying BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       date_buy TIMESTAMP WITH TIME ZONE NOT NULL,
                                       period_buy INTEGER NOT NULL,
                                       buy_status VARCHAR(50) NOT NULL,
    renew BOOLEAN NOT NULL DEFAULT FALSE,
    id_client BIGINT NOT NULL,
    id_vehicle BIGINT NOT NULL,

    CONSTRAINT fk_buying_client
    FOREIGN KEY (id_client)
    REFERENCES clients(id_client),

    CONSTRAINT fk_buying_vehicle
    FOREIGN KEY (id_vehicle)
    REFERENCES vehicles(id_vehicle),

    CONSTRAINT check_buying_period
    CHECK (period_buy > 0),

    CONSTRAINT check_buying_status
    CHECK (
              buy_status IN (
              'BEING_USED',
              'FINISHED'
                            )
    )
    );


-- ============================================
-- 9. TICKETS
-- ============================================

CREATE TABLE IF NOT EXISTS tickets (
                                       id_ticket BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       date_insert TIMESTAMP WITH TIME ZONE NOT NULL,
                                       status VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    tariff REAL,
    description VARCHAR(500) NOT NULL,
    id_client BIGINT,
    id_repair BIGINT,
    id_vehicle BIGINT,

    CONSTRAINT fk_ticket_client
    FOREIGN KEY (id_client)
    REFERENCES clients(id_client),

    CONSTRAINT fk_ticket_repair
    FOREIGN KEY (id_repair)
    REFERENCES repairs(id_repair),

    CONSTRAINT fk_ticket_vehicle
    FOREIGN KEY (id_vehicle)
    REFERENCES vehicles(id_vehicle),

    CONSTRAINT check_ticket_status
    CHECK (
              status IN (
              'ACCEPTED',
              'REJECTED',
              'PENDING', 'COMPLETED'
                        )
    ),

    CONSTRAINT check_ticket_type
    CHECK (
              type IN (
              'MODIFICATION',
              'REPARATION'
                      )
    ),

    CONSTRAINT check_ticket_price
    CHECK (tariff IS NULL OR tariff >= 0)
    );


-- ============================================
-- 10. DEMANDS
-- ============================================

CREATE TABLE IF NOT EXISTS demands (
                                       id_demand BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       date_ask TIMESTAMP WITH TIME ZONE NOT NULL,
                                       type VARCHAR(100) NOT NULL,
    status_confirm VARCHAR(50) NOT NULL,
    estimated_time INTEGER NOT NULL,
    id_supplier BIGINT,
    id_ticket BIGINT,
    id_vehicle BIGINT,

    CONSTRAINT fk_demand_supplier
    FOREIGN KEY (id_supplier)
    REFERENCES suppliers(id_supplier),

    CONSTRAINT fk_demand_ticket
    FOREIGN KEY (id_ticket)
    REFERENCES tickets(id_ticket),

    CONSTRAINT fk_demand_vehicle
    FOREIGN KEY (id_vehicle)
    REFERENCES vehicles(id_vehicle),

    CONSTRAINT check_demand_status
    CHECK (
              status_confirm IN (
              'APPROVED',
              'REFUSED',
              'PENDING'
                                )
    ),

    CONSTRAINT check_demand_estimated_time
    CHECK (estimated_time >= 0)
    );


-- ============================================
-- 11. REPAIR INFOS
-- ============================================

CREATE TABLE IF NOT EXISTS repair_infos (
                                            id_repair_info BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            date_start TIMESTAMP WITH TIME ZONE,
                                            repair_status VARCHAR(50) NOT NULL,
    id_repair BIGINT NOT NULL,
    id_vehicle BIGINT NOT NULL,

    CONSTRAINT fk_repair_info_repair
    FOREIGN KEY (id_repair)
    REFERENCES repairs(id_repair),

    CONSTRAINT fk_repair_info_vehicle
    FOREIGN KEY (id_vehicle)
    REFERENCES vehicles(id_vehicle),

    CONSTRAINT check_repair_status
    CHECK (
              repair_status IN (
              'PENDING_START',
              'PENDING_FINISH',
              'FINISHED',
              'CANCELLED'
                               )
    )
    );


-- ============================================
-- 12. SUBSCRIPTIONS
-- ============================================

CREATE TABLE IF NOT EXISTS subscriptions (
                                             id_subscription BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             date_start TIMESTAMP WITH TIME ZONE NOT NULL,
                                             price DOUBLE PRECISION NOT NULL,
                                             reduction INTEGER DEFAULT 0,
                                             subscription_type VARCHAR(50) NOT NULL,
    id_client BIGINT,
    id_supplier BIGINT,

    CONSTRAINT fk_subscription_client
    FOREIGN KEY (id_client)
    REFERENCES clients(id_client),

    CONSTRAINT fk_subscription_supplier
    FOREIGN KEY (id_supplier)
    REFERENCES suppliers(id_supplier),

    CONSTRAINT check_subscription_price
    CHECK (price >= 0),

    CONSTRAINT check_subscription_discount
    CHECK (reduction >= 0 AND reduction <= 100),

    CONSTRAINT check_subscription_type
    CHECK (
              subscription_type IN (
              'BASIC',
              'PREMIUM',
              'MONTHLY',
              'ANNUAL'
                                   )
    )
    );