DROP TABLE IF EXISTS demands CASCADE;

CREATE TABLE demands (

                         id_demand BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         date_ask TIMESTAMP WITH TIME ZONE NOT NULL,

                         type VARCHAR(50) NOT NULL,

                         status_confirm VARCHAR(30) NOT NULL,

                         estimated_time INTEGER NOT NULL,

                         id_supplier BIGINT NOT NULL,

                         id_ticket BIGINT NOT NULL,

                         id_vehicle BIGINT NOT NULL,

                         id_repair BIGINT NOT NULL,

                         id_client BIGINT NOT NULL,


    -- =========================================================
    -- FOREIGN KEYS
    -- =========================================================

                         CONSTRAINT fk_demand_supplier
                             FOREIGN KEY (id_supplier)
                                 REFERENCES suppliers(id_supplier),

                         CONSTRAINT fk_demand_ticket
                             FOREIGN KEY (id_ticket)
                                 REFERENCES tickets(id_ticket),

                         CONSTRAINT fk_demand_vehicle
                             FOREIGN KEY (id_vehicle)
                                 REFERENCES vehicles(id_vehicle),

                         CONSTRAINT fk_demand_repair
                             FOREIGN KEY (id_repair)
                                 REFERENCES repairs(id_repair),

                         CONSTRAINT fk_demand_client
                             FOREIGN KEY (id_client)
                                 REFERENCES clients(id_client),


    -- =========================================================
    -- ENUM VALIDATION
    -- =========================================================

                         CONSTRAINT check_demand_type
                             CHECK (
                                 type IN (
                                          'CONFIRMATION',
                                          'UPDATE'
                                     )
                                 ),

                         CONSTRAINT check_demand_status
                             CHECK (
                                 status_confirm IN (
                                                    'APPROVED',
                                                    'REFUSED',
                                                    'PENDING'
                                     )
                                 ),


    -- =========================================================
    -- ESTIMATED TIME
    -- =========================================================

                         CONSTRAINT check_demand_estimated_time
                             CHECK (estimated_time >= 0),


    -- =========================================================
    -- UNIQUE RELATION
    -- One client cannot have multiple demands
    -- for the same repair.
    -- =========================================================

                         CONSTRAINT uk_demand_client_repair
                             UNIQUE (id_client, id_repair)

);